spring:
  application:
    name: Blog-System
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Using Cloud SQL
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: boot
      password: spring

    # Google cloud storage and Cloud SQL
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: ${DB_NAME}
        instance-connection-name: ${INSTANCE_CONNECTION_NAME}
      project-id: ${GCP-PROJECT-ID}
      credentials:
        location: classpath:gcp/gcp-key.json
      storage:
        bucket: ${GCP_STORAGE_BUCKET_NAME}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
